2024-11-20 16:20:56,067 - 19269 - browsergym.experiments.loop - INFO - Running experiment DemoAgentArgs_on_workarena.servicenow.order-standard-laptop_16 in:
  results/2024-11-20_16-20-55_DemoAgentArgs_on_workarena.servicenow.order-standard-laptop_16
2024-11-20 16:20:56,647 - 19269 - browsergym.experiments.loop - WARNING - Exception uncaught by agent or environment in task workarena.servicenow.order-standard-laptop.
ValueError:
Please provide a ServiceNow instance URL (you can use the environment variable SNOW_INSTANCE_URL)
Traceback (most recent call last):
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 224, in run
    step_info.from_reset(
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 415, in from_reset
    self.obs, env_info = env.reset(seed=seed)
                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/gymnasium/wrappers/common.py", line 146, in reset
    return super().reset(seed=seed, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/gymnasium/core.py", line 328, in reset
    return self.env.reset(seed=seed, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/gymnasium/wrappers/common.py", line 400, in reset
    return super().reset(seed=seed, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/gymnasium/core.py", line 328, in reset
    return self.env.reset(seed=seed, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/core/env.py", line 193, in reset
    self.task = self.task_entrypoint(seed=seed, **self.task_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/workarena/tasks/service_catalog.py", line 619, in __init__
    super().__init__(
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/workarena/tasks/service_catalog.py", line 177, in __init__
    super().__init__(
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/workarena/tasks/base.py", line 66, in __init__
    self.instance = instance if instance is not None else SNowInstance()
                                                          ^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/browsergym_dev_env/lib/python3.12/site-packages/browsergym/workarena/instance.py", line 39, in __init__
    raise ValueError(
ValueError: Please provide a ServiceNow instance URL (you can use the environment variable SNOW_INSTANCE_URL)

2024-11-20 16:20:56,650 - 19269 - browsergym.experiments.loop - INFO - Saving summary info.
